app_name: "product-service"

rest:
  port: 8000

db:
  sqlx_config:
    driver: "postgres"
    master:
      address: "127.0.0.1"
      port: 5432
      db_name: "goproject"
      user: "ampazdev"
      password: "12345"
      ssl_mode: "disable"
    slave:
    - address: "127.0.0.1"
      port: 5432
      db_name: "goproject"
      user: "ampazdev"
      password: "12345"
      ssl_mode: "disable"