version: '3.1'
services:
  goproject_postgre:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: goproject
      POSTGRES_USER: ampazdev
      POSTGRES_PASSWORD: 12345
    volumes:
      - goproject_db_data:/var/lib/postgresql/data

volumes:
  goproject_db_data:
    driver: local